import * as auditActivity from "./audit-activity.js";
import * as auditRun from "./audit-run.js";
import * as audit from "./audit.js";
import * as config from "./config.js";
import * as humanMentions from "./human-mentions.js";
import * as carapace from "./carapace.js";
import * as taskSuggestions from "./task-suggestions.js";
import * as tasks from "./tasks.js";
import * as users from "./users.js";
import * as wizard from "./wizard.js";

export const OperationsProtocolSchemas = {
  AuditActivityAgentRunV1: auditActivity.AuditActivityAgentRunV1Schema,
  AuditActivityToolActionV1: auditActivity.AuditActivityToolActionV1Schema,
  AuditActivityInboundMessageV1: auditActivity.AuditActivityInboundMessageV1Schema,
  AuditActivityOutboundMessageV1: auditActivity.AuditActivityOutboundMessageV1Schema,
  AuditActivityEventV1: auditActivity.AuditActivityEventV1Schema,
  AuditActivityListParams: auditActivity.AuditActivityListParamsSchema,
  AuditActivityListResult: auditActivity.AuditActivityListResultSchema,
  ExecutionIdentityContextV1: auditRun.ExecutionIdentityContextV1Schema,
  DecisionReceiptV1: auditRun.DecisionReceiptV1Schema,
  DecisionReceiptDisplayV1: auditRun.DecisionReceiptDisplayV1Schema,
  AuditRunIdentityPresentV1: auditRun.AuditRunIdentityPresentV1Schema,
  AuditRunIdentityUnknownV1: auditRun.AuditRunIdentityUnknownV1Schema,
  AuditRunIdentityUnsupportedV1: auditRun.AuditRunIdentityUnsupportedV1Schema,
  AuditRunIdentityAmbiguousV1: auditRun.AuditRunIdentityAmbiguousV1Schema,
  AuditRunIdentityV1: auditRun.AuditRunIdentityV1Schema,
  AuditRunInspectParams: auditRun.AuditRunInspectParamsSchema,
  AuditRunInspectResult: auditRun.AuditRunInspectResultSchema,
  AuditEvent: audit.AuditEventSchema,
  AuditListParams: audit.AuditListParamsSchema,
  AuditListResult: audit.AuditListResultSchema,
  UserProfileAuthLink: users.UserProfileAuthLinkSchema,
  UserModelAccount: users.UserModelAccountSchema,
  UsersListModelAccountsParams: users.UsersListModelAccountsParamsSchema,
  UsersListModelAccountsResult: users.UsersListModelAccountsResultSchema,
  UsersSelectModelAccountParams: users.UsersSelectModelAccountParamsSchema,
  UsersSelectModelAccountResult: users.UsersSelectModelAccountResultSchema,
  ChatAccountSelection: users.ChatAccountSelectionSchema,
  UsersListAuthLinksParams: users.UsersListAuthLinksParamsSchema,
  UsersListAuthLinksResult: users.UsersListAuthLinksResultSchema,
  UsersLinkAuthProfileParams: users.UsersLinkAuthProfileParamsSchema,
  UsersLinkAuthProfileResult: users.UsersLinkAuthProfileResultSchema,
  UsersUnlinkAuthProfileParams: users.UsersUnlinkAuthProfileParamsSchema,
  UsersUnlinkAuthProfileResult: users.UsersUnlinkAuthProfileResultSchema,
  UsersAuthConnectCatalogParams: users.UsersAuthConnectCatalogParamsSchema,
  UsersAuthConnectCatalogResult: users.UsersAuthConnectCatalogResultSchema,
  UsersAuthConnectStartParams: users.UsersAuthConnectStartParamsSchema,
  UsersAuthConnectStartResult: users.UsersAuthConnectStartResultSchema,
  UsersAuthConnectAnswerParams: users.UsersAuthConnectAnswerParamsSchema,
  UsersAuthConnectStatusParams: users.UsersAuthConnectStatusParamsSchema,
  UsersAuthConnectCancelParams: users.UsersAuthConnectCancelParamsSchema,
  UsersAuthConnectStatusResult: users.UsersAuthConnectStatusResultSchema,
  UsersAuthConnectResult: users.UsersAuthConnectResultSchema,
  PersonalGitHubStatus: users.PersonalGitHubStatusSchema,
  UsersGitHubStatusParams: users.UsersGitHubStatusParamsSchema,
  UsersGitHubStatusResult: users.UsersGitHubStatusResultSchema,
  UsersGitHubAuthorizeStartParams: users.UsersGitHubAuthorizeStartParamsSchema,
  UsersGitHubAuthorizeStartResult: users.UsersGitHubAuthorizeStartResultSchema,
  UsersGitHubAuthorizePollParams: users.UsersGitHubAuthorizePollParamsSchema,
  UsersGitHubAuthorizePollResult: users.UsersGitHubAuthorizePollResultSchema,
  UsersGitHubAuthorizeCancelParams: users.UsersGitHubAuthorizeCancelParamsSchema,
  UsersGitHubAuthorizeCancelResult: users.UsersGitHubAuthorizeCancelResultSchema,
  UsersGitHubDisconnectParams: users.UsersGitHubDisconnectParamsSchema,
  UsersGitHubDisconnectResult: users.UsersGitHubDisconnectResultSchema,
  UsersPrefsChangedEvent: users.UsersPrefsChangedEventSchema,
  HumanMention: humanMentions.HumanMentionSchema,
  MentionableUser: humanMentions.MentionableUserSchema,
  UsersMentionableParams: humanMentions.UsersMentionableParamsSchema,
  UsersMentionableResult: humanMentions.UsersMentionableResultSchema,
  MentionInboxItem: humanMentions.MentionInboxItemSchema,
  MentionsListParams: humanMentions.MentionsListParamsSchema,
  MentionsDismissParams: humanMentions.MentionsDismissParamsSchema,
  MentionsListResult: humanMentions.MentionsListResultSchema,
  MentionsChangedEvent: humanMentions.MentionsChangedEventSchema,
  TaskSuggestion: taskSuggestions.TaskSuggestionSchema,
  TaskSuggestionEvent: taskSuggestions.TaskSuggestionEventSchema,
  TaskSuggestionResolution: taskSuggestions.TaskSuggestionResolutionSchema,
  TaskSuggestionsAcceptParams: taskSuggestions.TaskSuggestionsAcceptParamsSchema,
  TaskSuggestionsAcceptResult: taskSuggestions.TaskSuggestionsAcceptResultSchema,
  TaskSuggestionsCreateParams: taskSuggestions.TaskSuggestionsCreateParamsSchema,
  TaskSuggestionsCreateResult: taskSuggestions.TaskSuggestionsCreateResultSchema,
  TaskSuggestionsDismissParams: taskSuggestions.TaskSuggestionsDismissParamsSchema,
  TaskSuggestionsDismissResult: taskSuggestions.TaskSuggestionsDismissResultSchema,
  TaskSuggestionsListParams: taskSuggestions.TaskSuggestionsListParamsSchema,
  TaskSuggestionsListResult: taskSuggestions.TaskSuggestionsListResultSchema,
  TaskSummary: tasks.TaskSummarySchema,
  TasksListParams: tasks.TasksListParamsSchema,
  TasksListResult: tasks.TasksListResultSchema,
  TasksGetParams: tasks.TasksGetParamsSchema,
  TasksGetResult: tasks.TasksGetResultSchema,
  TasksCancelParams: tasks.TasksCancelParamsSchema,
  TasksCancelResult: tasks.TasksCancelResultSchema,
  TasksRecoveryParams: tasks.TasksRecoveryParamsSchema,
  TasksRecoveryResult: tasks.TasksRecoveryResultSchema,
  ConfigGetParams: config.ConfigGetParamsSchema,
  ConfigSetParams: config.ConfigSetParamsSchema,
  ConfigApplyParams: config.ConfigApplyParamsSchema,
  ConfigPatchParams: config.ConfigPatchParamsSchema,
  ConfigSchemaParams: config.ConfigSchemaParamsSchema,
  ConfigSchemaLookupParams: config.ConfigSchemaLookupParamsSchema,
  ConfigSchemaResponse: config.ConfigSchemaResponseSchema,
  ConfigSchemaLookupResult: config.ConfigSchemaLookupResultSchema,
  SystemAgentChatParams: carapace.SystemAgentChatParamsSchema,
  SystemAgentChatResult: carapace.SystemAgentChatResultSchema,
  SystemAgentChatHistoryParams: carapace.SystemAgentChatHistoryParamsSchema,
  SystemAgentChatHistoryTurn: carapace.SystemAgentChatHistoryTurnSchema,
  SystemAgentChatHistoryResult: carapace.SystemAgentChatHistoryResultSchema,
  SystemChangeEntry: carapace.SystemChangeEntrySchema,
  SystemChangeKind: carapace.SystemChangeKindSchema,
  SystemChangeSource: carapace.SystemChangeSourceSchema,
  SystemChangesListParams: carapace.SystemChangesListParamsSchema,
  SystemChangesListResult: carapace.SystemChangesListResultSchema,
  SystemAgentSetupDetectParams: carapace.SystemAgentSetupDetectParamsSchema,
  SystemAgentSetupDetectResult: carapace.SystemAgentSetupDetectResultSchema,
  SystemAgentSetupVerifyParams: carapace.SystemAgentSetupVerifyParamsSchema,
  SystemAgentSetupVerifyResult: carapace.SystemAgentSetupVerifyResultSchema,
  SystemAgentSetupActivateParams: carapace.SystemAgentSetupActivateParamsSchema,
  SystemAgentSetupActivateResult: carapace.SystemAgentSetupActivateResultSchema,
  SystemAgentSetupActivateStartParams: carapace.SystemAgentSetupActivateStartParamsSchema,
  SystemAgentSetupActivateStartResult: carapace.SystemAgentSetupActivateStartResultSchema,
  SystemAgentSetupAuthStartParams: carapace.SystemAgentSetupAuthStartParamsSchema,
  SystemAgentSetupAuthStartResult: carapace.SystemAgentSetupAuthStartResultSchema,
  WizardStartParams: wizard.WizardStartParamsSchema,
  WizardNextParams: wizard.WizardNextParamsSchema,
  WizardCancelParams: wizard.WizardCancelParamsSchema,
  WizardStatusParams: wizard.WizardStatusParamsSchema,
  WizardStep: wizard.WizardStepSchema,
  WizardNextResult: wizard.WizardNextResultSchema,
  WizardStartResult: wizard.WizardStartResultSchema,
  WizardStatusResult: wizard.WizardStatusResultSchema,
} as const;
